// <auto-generated />
using System;
using KolokwiumCodeFirst.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KolokwiumCodeFirst.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250610124330_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KolokwiumCodeFirst.Models.Map", b =>
                {
                    b.Property<int>("MapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MapId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MapId");

                    b.ToTable("Map");

                    b.HasData(
                        new
                        {
                            MapId = 1,
                            Name = "Inferno",
                            Type = "a"
                        },
                        new
                        {
                            MapId = 2,
                            Name = "Mirage",
                            Type = "b"
                        },
                        new
                        {
                            MapId = 3,
                            Name = "Map",
                            Type = "a"
                        });
                });

            modelBuilder.Entity("KolokwiumCodeFirst.Models.Match", b =>
                {
                    b.Property<int>("MatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MatchId"));

                    b.Property<double?>("BestRating")
                        .HasPrecision(10, 2)
                        .HasColumnType("float(10)");

                    b.Property<int>("MapId")
                        .HasColumnType("int");

                    b.Property<DateTime>("MatchDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Team1Score")
                        .HasColumnType("int");

                    b.Property<int>("Team2Score")
                        .HasColumnType("int");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.HasKey("MatchId");

                    b.HasIndex("MapId");

                    b.HasIndex("TournamentId");

                    b.ToTable("Match");

                    b.HasData(
                        new
                        {
                            MatchId = 1,
                            BestRating = 3.0,
                            MapId = 1,
                            MatchDate = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Team1Score = 5,
                            Team2Score = 5,
                            TournamentId = 1
                        },
                        new
                        {
                            MatchId = 2,
                            BestRating = 2.3999999999999999,
                            MapId = 2,
                            MatchDate = new DateTime(2023, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Team1Score = 4,
                            Team2Score = 4,
                            TournamentId = 2
                        },
                        new
                        {
                            MatchId = 3,
                            BestRating = 1.0,
                            MapId = 3,
                            MatchDate = new DateTime(2024, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Team1Score = 1,
                            Team2Score = 2,
                            TournamentId = 3
                        });
                });

            modelBuilder.Entity("KolokwiumCodeFirst.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerId"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PlayerId");

                    b.ToTable("Player");

                    b.HasData(
                        new
                        {
                            PlayerId = 1,
                            BirthDate = new DateTime(2005, 1, 2, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Alex",
                            LastName = "Nowak"
                        },
                        new
                        {
                            PlayerId = 2,
                            BirthDate = new DateTime(2015, 7, 2, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Piotr",
                            LastName = "Smith"
                        },
                        new
                        {
                            PlayerId = 3,
                            BirthDate = new DateTime(2004, 2, 2, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Zofia",
                            LastName = "Cocos"
                        });
                });

            modelBuilder.Entity("KolokwiumCodeFirst.Models.Player_Match", b =>
                {
                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("MVPs")
                        .HasColumnType("int");

                    b.Property<double>("Rating")
                        .HasPrecision(10, 2)
                        .HasColumnType("float(10)");

                    b.HasKey("MatchId", "PlayerId");

                    b.HasIndex("PlayerId");

                    b.ToTable("Player_Match");

                    b.HasData(
                        new
                        {
                            MatchId = 1,
                            PlayerId = 1,
                            MVPs = 1,
                            Rating = 10.99
                        },
                        new
                        {
                            MatchId = 2,
                            PlayerId = 2,
                            MVPs = 2,
                            Rating = 41.5
                        },
                        new
                        {
                            MatchId = 3,
                            PlayerId = 3,
                            MVPs = 3,
                            Rating = 3.75
                        });
                });

            modelBuilder.Entity("KolokwiumCodeFirst.Models.Tournament", b =>
                {
                    b.Property<int>("TournamentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TournamentId"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("TournamentId");

                    b.ToTable("Tournamen");

                    b.HasData(
                        new
                        {
                            TournamentId = 1,
                            EndDate = new DateTime(2025, 8, 2, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "CS2 Summer Cup",
                            StartDate = new DateTime(2025, 7, 2, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TournamentId = 2,
                            EndDate = new DateTime(2025, 9, 2, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "CS2 Summer Cup",
                            StartDate = new DateTime(2025, 3, 2, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TournamentId = 3,
                            EndDate = new DateTime(2025, 10, 2, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "CS2 Summer Cup",
                            StartDate = new DateTime(2025, 4, 2, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("KolokwiumCodeFirst.Models.Match", b =>
                {
                    b.HasOne("KolokwiumCodeFirst.Models.Map", "Map")
                        .WithMany("Match")
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KolokwiumCodeFirst.Models.Tournament", "Tournament")
                        .WithMany("Match")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Map");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("KolokwiumCodeFirst.Models.Player_Match", b =>
                {
                    b.HasOne("KolokwiumCodeFirst.Models.Match", "Match")
                        .WithMany("PlayerMatch")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KolokwiumCodeFirst.Models.Player", "Player")
                        .WithMany("PlayerMatch")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("KolokwiumCodeFirst.Models.Map", b =>
                {
                    b.Navigation("Match");
                });

            modelBuilder.Entity("KolokwiumCodeFirst.Models.Match", b =>
                {
                    b.Navigation("PlayerMatch");
                });

            modelBuilder.Entity("KolokwiumCodeFirst.Models.Player", b =>
                {
                    b.Navigation("PlayerMatch");
                });

            modelBuilder.Entity("KolokwiumCodeFirst.Models.Tournament", b =>
                {
                    b.Navigation("Match");
                });
#pragma warning restore 612, 618
        }
    }
}
